name: simple_time_range_picker
description: A simple time range picker for flutter
version: 0.0.5
repository: https://github.com/trashfeed/simple_time_range_picker
issue_tracker: https://github.com/trashfeed/simple_time_range_picker/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
